Vagrant.configure("2") do |config|
  config.vm.box = "fedora/38-cloud-base"
  config.vm.box_version = "38.20230413.1"
  
  ["virtualbox", "libvirt"].each do |provider|
    config.vm.provider provider do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end
  
  config.vm.provision "shell", inline: "cd /vagrant/files/ && bash ./softhsm-node.sh"
end
